services:
  - type: web
    name: yt-downloader-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PORT
        value: 10000
